spring:
  datasource:
    url: jdbc:h2:mem:mancaladb
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  session:
    store-type: jdbc